import type { Metadata } from "next";
import { Inter, Press_Start_2P, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { SessionProvider } from "../components/SessionProvider";
import { getServerSession } from "next-auth";
import Login from "../components/Login";
import { authOptions } from "@/auth";
import ToasterClientProvider from "@/components/ToasterClientProvider";

const inter = Inter({ subsets: ["latin"] });

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

const press_start = Press_Start_2P({
  subsets: ["latin"],
  display: "swap",
  variable: "--press-start",
  weight: "400",
});

export const metadata: Metadata = {
  title: "LingoChallenge",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html
      lang="en"
      className={`${roboto_mono.variable} ${press_start.variable} bg-gray-200  `}
    >
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex space-x-3.5 bg-gray-200 h-screen px-3.5 ">
              <div className="my-3.5 bg-white max-w-xs overflow-y-auto md:min-w-[15rem] rounded-xl">
                <Sidebar />
              </div>

              <ToasterClientProvider />

              <div className="my-3.5 bg-white flex-1 rounded-xl overflow-y-auto// overflow-y-hidden ">
                {children}
              </div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
